### ISSUE TITLE
Improvement. Add tilewide patch

### ISSUE THREAD

**Issue by spavlovich001** [bakkeby/dwm-flexipatch#326] opened 2023-01-14 18:45 UTC
Do you plan to add this wonderful patch? https://dwm.suckless.org/patches/tilewide/

**Comment by bakkeby** [comment] 2023-01-14 19:20
No I believe that is just a duplicate of the columns patch (a.k.a col layout):
https://dwm.suckless.org/patches/columns/

**Closed** 2023-01-14 20:44 UTC
