### ISSUE TITLE
Add alwayscenter patch

### ISSUE THREAD

**Issue by 766F6964** [bakkeby/dwm-flexipatch#182] opened 2021-09-07 23:07 UTC
Is it possible to add support for the alwayscenter patch? (https://dwm.suckless.org/patches/alwayscenter/)
It essentially centers new floating windows without any rules. 
Should be fairly easy to add, since it is only two lines.

**Comment by bakkeby** [comment] 2021-09-08 08:33
Yes it is a simple patch. Simplicity also comes with limits of course.

Because it is so simple it, as the name suggests, applies to all floating windows indiscriminately. To me that does not make it a good patch as it removes flexibility, but that is of course subjective.

Some applications have size hints that specifies where they are to start and some applications can remember where their windows were last time before it closed and will attempt to open them there again. The patch will take those features away when it forces all windows to be centered.

If you use gimp as an example then you may find that unless you are running in Single-Window Mode then all external docs / tool bars are placed on top of each other in the center of the screen.

The patch of course also affects dialog boxes, popups and transient windows. I suspect the feature is more practical on small screens / laptops.

It should also be noted that client messages can come through for the window telling the window manager to move it somewhere else. This would likely be the cause if a floating window is not centered when it is first shown.

For reference there are two other variations (or ideas) of this patch as well.

```c
if (c->x == c->mon->wx && c->y == c->mon->wy) {
	c->x = c->mon->wx + (c->mon->ww - WIDTH(c)) / 2;
	c->y = c->mon->wy + (c->mon->wh - HEIGHT(c)) / 2;
}
```
The above will center the window, but only if it does not have any size hints and thus is positioned by default in the top left corner of the screen.

```c
int x, y;
if (getrootptr(&x, &y)) {
	c->x = x - WIDTH(c) / 2;
	c->y = y - HEIGHT(c) / 2;
}
```
The above will place the window so that the center of the window is where the mouse cursor is currently pointing. This is obviously for mouse centric users.

**Comment by 766F6964** [comment] 2021-09-08 09:18
Thanks for the reply. You are right, there are definitely use-cases where this wouldn't be the ideal behavior.
My intention was also to mainly use this for terminal windows (Kinda like a scratchpad).
Is there already an implementation present that allows for centering floating windows, with some restrictions. (E.g. only windows with certain names etc) ?
If not, adding a more fine-grained variant of this would probably make sense.

**Comment by bakkeby** [comment] 2021-09-08 09:31
There is naturally the [center](https://dwm.suckless.org/patches/center/) patch which adds a rule option to center windows. There are also rule options for the [floatpos](https://github.com/bakkeby/dusk/wiki/floatpos) patch as well.

**Comment by 766F6964** [comment] 2021-09-08 09:47
Alright. I was already looking into the center-patch earlier, but I couldn't get it to work.
Most likely I am doing something wrong. I did enable the patch in the `patches.h` file, however, spawning new windows in floating mode still remain in the top left, instead of the center of the screen.
All I am trying to do, is that new terminal windows, when spawned in floating mode, should appear in the center of the current monitor.
Do you have any idea what I am doing wrong?

**Comment by bakkeby** [comment] 2021-09-08 09:54
Have you set up any client rules for the terminal window?

You'd want to add `, .iscentered = 1` to the rule in that case (unless you are using a traditional table structure).

**Comment by 766F6964** [comment] 2021-09-08 10:02
Good point, I did not specify that explicitly. I have no added the following rule:
`RULE(.class = "st", .isfloating = 1, .iscentered = 1)`
However, spawning a new st window when in floating mode still does not center it.

It might be worth mentioning that I barely did any modifications on this dwm build so far, I mainly customized keybinding, so most of the other stuff should be vanilla.

**Comment by bakkeby** [comment] 2021-09-08 10:12
Does the window start as floating?

If not then you may want to double check the WM_CLASS of your st window using xprop.

E.g. in this case the class is capitalised as St whereas the instance name is in lower case.
```
WM_CLASS(STRING) = "st", "St"
```

**Comment by 766F6964** [comment] 2021-09-08 13:41
Okay, this got me one step further. However, now every st instance that I spawn is floating and centered.
That's not quite what I want. I want the st instance to be floating and centered if floating mode is enabled.
Right now, it does this, regardless if I have the floating layout (`><>`) or the stack layout (`[]=`) selected.

My rule looks like this:
`RULE(.class = "St", .isfloating = 1, .iscentered = 1)`

**Comment by bakkeby** [comment] 2021-09-08 14:06
Yes that's something different, these rules only affect the placement of the window when it is first spawned.

You can use the savefloats patch to save the float position of windows (when you move them around), but there isn't anything there out of the box to pre-save a centered position.

I suppose I could add something like that if the window is marked as .iscentered = 1 and it is tiled.

**Comment by 766F6964** [comment] 2021-09-08 15:02
Yeah, sounds like it would be a nice addition.

**Comment by bakkeby** [comment] 2021-09-08 15:21
Can you try the above? I did a quick check and it seemed to work fine.

**Comment by 766F6964** [comment] 2021-09-08 15:34
Hmm, I still get the same behavior, that every st instance is floating and centered.
What patches did you enable exactly? Did you change anything else?

**Comment by bakkeby** [comment] 2021-09-08 16:19
Your client rule still says .isfloating = 1 right, which is why st starts as floating. If you remove that or set it to 0 then st will be tiled by default.

The change is that when you then make it floating, via the floating layout or via togglefloating, then it should be centered.

**Comment by bakkeby** [comment] 2021-09-08 16:45
To clarify this is using the savefloats patch in combination with the center or alwayscenter patch.

**Comment by 766F6964** [comment] 2021-09-08 19:34
Well, is there a way to prevent the existing windows to all stack when switching to floating mode?
Again, the idea is to simply get something like a scratchpad in the middle of the screen, when spawning a st window. This should of course overlay the existing windows. 
However, right now, all existing st-windows in the workspace get stacked on top of each other in the center.
In short: The behavior is now correct, however, it should only apply to new windows that get spawned, and leave the existing ones untouched.
Do you have an idea how I can change that?

**Comment by haluk** [comment] 2021-09-08 23:00
I'm receiving the following error. I'm not sure if it's related with this path:

```
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/include/X11 -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/lib/X11 -lX11 -lXinerama -lfontconfig -lXft  -lXrender   -lX11-xcb -lxcb -lxcb-res
CC       = cc
cp config.def.h config.h
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/include/X11 -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/include/X11 -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c
dwm.c: In function ‘manage’:
dwm.c:1541:14: error: ‘Client’ has no member named ‘iscentered’
 1541 |         if (c->iscentered) {
      |              ^~
In file included from patch/include.c:2,
                 from dwm.c:434:
At top level:
patch/bar_indicators.c:97:1: warning: ‘drawstateindicator’ defined but not used [-Wunused-function]
   97 | drawstateindicator(Monitor *m, Client *c, unsigned int occ, int x, int y, int w, int h, unsigned int tag, int filled, int invert)
      | ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:24: dwm.o] Error 1
```

**Comment by bakkeby** [comment] 2021-09-09 06:51
Hi @haluk, I guess flexipatch-finalizer is not that good with parentheses. I tried expanding them instead, can you try with the above?

**Comment by bakkeby** [comment] 2021-09-09 07:11
@766F6964 you can specify the instance and class of st when you start it, e.g.

```
$ st -n Otherwordly -c Example
```

then if you do `xprop` on the window you will have:
```
WM_CLASS(STRING) = "Otherwordly", "Example"
```

and like this you can have different rules depending on what class or instance you specify.

This is also how you do it if you define separate scratchpads.

**Comment by haluk** [comment] 2021-09-09 13:30
> Hi @haluk, I guess flexipatch-finalizer is not that good with parentheses. I tried expanding them instead, can you try with the above?

@bakkeby That fixed it. Thanks.

**Closed** 2021-09-23 11:26 UTC
