### ISSUE TITLE
add bidi patch

### ISSUE THREAD

**Issue by h45h1r** [bakkeby/dwm-flexipatch#285] opened 2022-08-01 10:17 UTC
these patches bidi, stickyindicator, singularborders, alwaysontop, titlecolor aren't currently added. 
would it be fine to manually patch them in the meanwhile?

**Comment by bakkeby** [comment] 2022-08-01 14:30
Quick analysis.

[bidi](https://dwm.suckless.org/patches/bidi/)
   - this may potentially be cumbersome to integrate due to conflicting with so many other patches, e.g. status2d, powerline status, statuscmd, statuscolors, powerline tags to name a few
   - but I think that it should be doable
   - has a performance implication of course

[stickyindicator](https://dwm.suckless.org/patches/stickyindicator/)
   - should be trivial to add I'd imagine

[singular borders](https://dwm.suckless.org/patches/singularborders/)
   - this is a particularly bad patch which overlaps windows with the aim of hiding the border
   - additionally the client borders will bleed across to adjacent monitors
   - this conflicts with every available layout and would be considered as out of scope for dwm-flexipatch as it would be way too invasive
   - it should be noted that this behaviour is reproducible using the vanitygaps patch, e.g. set `borderpx` to 5, `gappih` and `gappiv` to -5, then `gappoh` and `gappov` to 0 (just needs the change to the `focus` function to make sure the focused window is placed above the others)

[alwaysontop](https://dwm.suckless.org/patches/alwaysontop/)
   - relatively simple patch
   - adds another indicator
   - patch itself could probably be simplified
   - curiously only allows a single window to be always on top
   - seems like a candidate for integration

[titlecolor](https://dwm.suckless.org/patches/titlecolor/)
   - adds a new (separate) colour scheme for the window title in the bar
   - this is already covered by the `SchemeTitleSel` and `SchemeTitleNorm` colour schemes

**Comment by h45h1r** [comment] 2022-08-01 16:25
Thanks for the reply
Will bidi be added at some point ?

**Comment by bakkeby** [comment] 2022-08-02 09:02
I added the bidi feature in a different way than was proposed in the patch. This applies to all text printed on the bar.

I did a quick test and it seems to work just fine.

**Comment by h45h1r** [comment] 2022-08-02 09:37
Thanks alot

**Comment by h45h1r** [comment] 2022-08-03 21:02
i

**Comment by h45h1r** [comment] 2022-08-03 21:05
i compiled the dwm with the bidi patch 
and i got this error 
`drw.c:13:10: fatal error: fribidi.h: No such file or directory
   13 | #include <fribidi.h>`

**Comment by bakkeby** [comment] 2022-08-03 22:12
I suppose that it assumes that you have the headers for the library installed.

**Comment by h45h1r** [comment] 2022-08-04 17:03
i fixed it by changing the header file path
i'm getting this error now 
`/usr/bin/ld: drw.o: in function `apply_fribidi':
drw.c:(.text+0x1f4): undefined reference to `fribidi_parse_charset'
/usr/bin/ld: drw.c:(.text+0x20e): undefined reference to `fribidi_charset_to_unicode'
/usr/bin/ld: drw.c:(.text+0x22b): undefined reference to `fribidi_log2vis'
/usr/bin/ld: drw.c:(.text+0x23e): undefined reference to `fribidi_unicode_to_charset'
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: dwm] Error 1`

**Comment by bakkeby** [comment] 2022-08-04 18:11
Doesn't sound like you fixed it :D

What distribution are you on?

**Comment by h45h1r** [comment] 2022-08-04 19:55
> What distribution are you on?
arch linux

**Comment by bakkeby** [comment] 2022-08-04 21:46
Some patches have dependencies on additional libraries. In the case of the bidi patch this has a dependency on the fribidi library. More so because it is _compiling_ against that library it needs the header files which may be included in the normal library, but sometimes it is included in a separate dev library.

You know the name of the header file which is `fribidi.h`. If you are unsure if you have this header file then you can search for it using the package manager for your distribution, e.g.

```sh
$ pacman -F fribidi.h
extra/fribidi 1.0.10-1 [installed: 1.0.12-1]
    usr/include/fribidi/fribidi.h
```

or the same if you are using paru:

```sh
$ paru -F fribidi.h
extra/fribidi 1.0.10-1 [installed: 1.0.12-1]
    usr/include/fribidi/fribidi.h
```

Most likely you already have this installed as it looks like a lot of things depend on this library.

The next is that this library needs to be included as part of the compilation process. This is managed in `config.mk` which handles the configurable aspects of the Makefile.

Not everyone uses every library, hence optional libraries are commented out by default:
https://github.com/bakkeby/dwm-flexipatch/blob/10aa27171f87b88bfb48747e9d57361ec7bdaacd/config.mk#L54-L56

Once you have uncommented those two lines and you have enabled the `BIDI_PATCH` toggle in your `patches.h` file then it should in principle compile fine.

https://github.com/bakkeby/dwm-flexipatch/blob/10aa27171f87b88bfb48747e9d57361ec7bdaacd/patches.def.h#L493-L503

**Comment by h45h1r** [comment] 2022-08-04 23:33
thank you so much 
it works and compiled fine

**Closed** 2022-08-04 23:34 UTC
