### ISSUE TITLE
missleading variable?

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#2] opened 2020-01-12 16:49 UTC
when including vanitygaps patch on top of the listed patches bellow I get this make error
`CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA dwm.c
In file included from patch/include.c:179,
                 from dwm.c:470:
patch/tile.c: In function ‘tile’:
patch/tile.c:12:2: warning: implicit declaration of function ‘getgaps’; did you mean ‘setgaps’? [-Wimplicit-function-declaration]
   12 |  getgaps(m, &oh, &ov, &ih, &iv, &n);
      |  ^~~~~~~
      |  setgaps
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
/usr/bin/ld: dwm.o: in function `tile':
dwm.c:(.text+0xc1e): undefined reference to `getgaps'
collect2: error: ld returned 1 exit status
make: *** [Makefile:26: dwm] Error 1
`
patches included in this error are
patches that I have enabled
ALPHA
ATTACHBOTTOM
AUTORESIZE
AWESOMEBAR
CENTER
CFACTS
CYCLELAYOUTS
EWMHTAGS
HIDEVACANTTAGS
IGNORE_XFT_ERRORS_WHEN_DRAWING_TEXT
MOVESTACK
NODMENU
PERTAG
SCRATCHPAD
SYSTRAY
SWITCHTAG
TOGGLEFULLSCREEN
VANITYGAPS
WINDOWROLERULE
ZOOMSWAP

and it wont build
------------

patches included in 2nd error are
ALPHA
ATTACHBOTTOM
AUTORESIZE
AWESOMEBAR
CENTER
CFACTS
CYCLELAYOUTS
EWMHTAGS
HIDEVACANTTAGS
IGNORE_XFT_ERRORS_WHEN_DRAWING_TEXT
MOVESTACK
NODMENU
PERTAG
SCRATCHPAD
SYSTRAY
SWITCHTAG
TOGGLEFULLSCREEN
VANITYGAPS
WINDOWROLERULE
ZOOMSWAP
CENTEREDMASTER_LAYOUT
DECK_LAYOUT
MONOCLE_LAYOUT
TILE_LAYOUT

and ran the flexipatch finalizer on top of the 2nd combination of patches

```
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
CC       = cc
cp config.def.h config.h
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA dwm.c
dwm.c: In function ‘zoom’:
dwm.c:2377:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
 2377 |  if (!selmon->lt[selmon->sellt]->arrange
      |  ^~
dwm.c:2383:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
 2383 |   if (c == nexttiled(selmon->clients)) {
      |   ^~
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
```

I have no clue what this means mate
or how to fix it

**Comment by kronikpillow** [comment] 2020-01-12 16:55
the 2nd error only happens if i run flexipatch finalizer

this is how I ran it

bash flexipatch-finalizer.sh -r in the directory of dwm-flexipatch

**Comment by bakkeby** [comment] 2020-01-15 12:31
Thanks, the first issue was a legitimate bug relating to using only the original tile layout. The second issue was indeed the zoomswap patch, caused by was bad indentation. It did compile successfully though.

I committed a fix for both of these issues so you shouldn't see these anymore. Sorry for the delay.

**Closed by bakkeby** 2020-01-15 12:31 UTC

**Comment by kronikpillow** [comment] 2020-01-15 13:05
np :) thanks
